### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by renkun-ken** [jeroen/protolite#4]
I installed the dependent libraries as follows:

```
sudo apt-get install -y libprotobuf-dev protobuf-compiler
Reading package lists... Done
Building dependency tree       
Reading state information... Done
protobuf-compiler is already the newest version (2.6.1-1.3).
The following NEW packages will be installed:
  libprotobuf-dev
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 473 kB of archives.
After this operation, 3,811 kB of additional disk space will be used.
Get:1 http://mirrors.aliyun.com/ubuntu xenial/main amd64 libprotobuf-dev amd64 2.6.1-1.3 [473 kB]
Fetched 473 kB in 0s (879 kB/s)         
Selecting previously unselected package libprotobuf-dev:amd64.
(Reading database ... 197538 files and directories currently installed.)
Preparing to unpack .../libprotobuf-dev_2.6.1-1.3_amd64.deb ...
Unpacking libprotobuf-dev:amd64 (2.6.1-1.3) ...
Setting up libprotobuf-dev:amd64 (2.6.1-1.3) ...
```

but the package still fails to install:

```
Found pkg-config cflags and libs!
Using PKG_CFLAGS=-pthread
Using PKG_LIBS=-lprotobuf -pthread -lpthread
Failed to run protoc.
Please install the 'protobuf-compiler' package for your system.
ERROR: configuration failed for package ‘protolite’
* removing ‘/home/renkun/R/x86_64-pc-linux-gnu-library/3.3/protolite’
Warning in install.packages :
  installation of package ‘protolite’ had non-zero exit status
```

My info:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

```
R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.3 yaml_2.1.14
```

**Comment by jeroen** [comment]
Hmz strange. Is `protoc` on your path?

```
protoc --version
```

**Comment by renkun-ken** [comment]
`protoc` is not on my path. It does not seem to proceed automatically when installed.

**Comment by jeroen** [comment]
Very strange, the `protobuf-compiler` package should install `/usr/bin/protoc`:

  http://packages.ubuntu.com/xenial/amd64/protobuf-compiler/filelist

So if you have this package installed `protoc` should be on the path.

**Comment by jeroen** [comment]
This must have been a local problem. Our travis is configured to test on both linux and osx, and `protoc` is always on the path.

**Comment by leandrocara** [comment]
Hi I have similar problem, and can't find a solution on the web: 
I have Installed the libraries libprotobuf-dev, protobuf-compiler and protobuf-c-compiler, by apt-get and from source, and have the same result. 

> install.packages('protolite', repos='https://cran.rstudio.com/')
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
probando la URL 'https://cran.rstudio.com/src/contrib/protolite_2.0.tar.gz'
Content type 'application/x-gzip' length 24832 bytes (24 KB)
==================================================
downloaded 24 KB

* installing *source* package ‘protolite’ ...
** package ‘protolite’ successfully unpacked and MD5 sums checked
Found pkg-config cflags and libs!
Using: ERROR: no information for variable 'CXX11' -std=gnu++11 -E
Using PKG_CFLAGS=-pthread
Using PKG_LIBS=-lprotobuf -pthread -lpthread
./configure: línea 57: ERROR:: no se encontró la orden
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because protobuf was not found. Try installing:
 * deb: libprotobuf-dev (Debian, Ubuntu, etc)
 * rpm: protobuf-devel (Fedora, EPEL)
 * csw: protobuf_dev (Solaris)
 * brew: protobuf (OSX)
If protobuf is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a protobuf.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------

~# protoc --version 
libprotoc 3.0.0

~# apt-get install libprotobuf-dev
Leyendo lista de paquetes... Hecho
Creando árbol de dependencias       
Leyendo la información de estado... Hecho
libprotobuf-dev ya está en su versión más reciente (3.0.0-9).
0 actualizados, 0 nuevos se instalarán, 0 para eliminar y 0 no actualizados.

My session: 

> sessionInfo( )
R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

locale:
 [1] LC_CTYPE=es_AR.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=es_AR.UTF-8        LC_COLLATE=es_AR.UTF-8    
 [5] LC_MONETARY=es_AR.UTF-8    LC_MESSAGES=es_AR.UTF-8   
 [7] LC_PAPER=es_AR.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=es_AR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base    

If you can help me I would be very thankful

**Comment by jeroen** [comment]
Can you upgrade R to a more recent version?  It seems to not find `CXX11`

**Comment by leandrocara** [comment]
Many thanks, I upgraded my R and that solved my problem. Thanks again
